name: Create Review App on Render

on:
  pull_request:
    branches:
      - main

jobs:
  create_review_app:
    name: Create Review App
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Review App
        uses: renderapp/render-deploy-action@v1.2.0
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          branch: ${{ github.event.pull_request.head.ref }}
          subdomain: pr-${{ github.event.pull_request.number }}
